export const ReducerConstants = {
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_SUCCESS_NOTIFICATION: "SHOW_SUCCESS_NOTIFICATION",
  SHOW_ERROR_NOTIFICATION: "SHOW_ERROR_NOTIFICATION",
  SHOW_WARNING_NOTIFICATION: "SHOW_WARNING_NOTIFICATION",
  SHOW_INFO_NOTIFICATION: "SHOW_INFO_NOTIFICATION",
  HIDE_NOTIFICATION: "HIDE_NOTIFICATION",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  START_LOGIN:'START_LOGIN',
  
};
export default {};
